name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: octalysis-tool/package-lock.json

      - name: Install dependencies
        working-directory: octalysis-tool
        run: npm ci

      - name: Build
        working-directory: octalysis-tool
        run: npm run build -- --base-href /OctalysisTool/

      - name: Resolve dist path
        id: resolve_dist
        run: |
          set -e
          if [ -f "octalysis-tool/dist/octalysis-tool/index.html" ]; then
            echo "dir=octalysis-tool/dist/octalysis-tool" >> $GITHUB_OUTPUT
          elif [ -f "octalysis-tool/dist/octalysis-tool/browser/index.html" ]; then
            echo "dir=octalysis-tool/dist/octalysis-tool/browser" >> $GITHUB_OUTPUT
          else
            echo "index.html not found in expected dist locations" >&2
            echo "Dist tree:" >&2
            ls -la octalysis-tool/dist || true
            ls -la octalysis-tool/dist/octalysis-tool || true
            exit 1
          fi

      - name: Add SPA fallback (404.html)
        run: cp "${{ steps.resolve_dist.outputs.dir }}/index.html" "${{ steps.resolve_dist.outputs.dir }}/404.html"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.resolve_dist.outputs.dir }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
